name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Install system dependencies for Bevy (audio, input, graphics)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libudev-dev \
            libx11-dev \
            libxi-dev \
            libgl1-mesa-dev \
            pkg-config

      # Install Rust stable toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache Cargo dependencies
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build project
      - name: Build
        run: cargo build --verbose

      # Run tests (if you add unit tests)
      - name: Run tests
        run: cargo test --verbose

      # Enforce formatting
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Lint with Clippy (fail on warnings)
      - name: Run Clippy
        run: cargo clippy -- -D warnings